### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by helinb** [F1ash/qt-virt-manager#1]
-- Found GObject includes : /usr/include/glib-2.0/gobject
CMake Error at /usr/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Spice1 (missing: Spice1_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSpice1.cmake:26 (find_package_handle_standard_args)
  CMakeLists.txt:640 (find_package)

**Comment by F1ash** [comment]
https://github.com/F1ash/qt-virt-manager/blob/master/qt-virt-manager.spec#L38-L40
you need to install spice-protocol (v.0.12.7 : Spice protocol header files) for build.
