### ISSUE TITLE
build without libcacard

### ISSUE THREAD

**Issue by mcirsta** [F1ash/qt-virt-manager#11]
Given the recent split of libcacard from qemu I've decided not to have it on my system since I don't really need it ( I guess few people really do ? ).
 Spice knows how to build without libcacard ( which is how I buit it ) but qt-virt-manager requires libcacard.
 I've managed to make several modification to build without libcacard ( make it optional ) but I'm not sure these are how you want to do it as they're mostly just ifdefs in the code. I can clean it up a bit and send a pull request if you want though.

**Comment by F1ash** [comment]
i did returning some changes in qsmartcardmanager.cpp.
If you implement changes as additional build parameter (for ex. WITHOUT_LIBCACARD), then do it from current point.

**Comment by F1ash** [comment]
fixed.

**Comment by mcirsta** [comment]
Thank you, this helps.
