### ISSUE TITLE
qml addition

### ISSUE THREAD

**Issue by Dravigon** [F1ash/qt-virt-manager#16]
since qml is out why dont u use qml it adds a extra look to ui

**Comment by F1ash** [comment]
rewriting on qml is difficult , because it need many time, it need rewrite whole code, not part by part...  Maybe you have some suggestions about features for new -- SoftTouched mode.

**Comment by mcirsta** [comment]
Having worked with QML I can assure you that while it might look nice from a (C++) developer point of view it's not that easy to use.
 Overall for this application I'd say a QML interface is really not needed or worth the effort, this is not about looks and it's not for mobile.
