### ISSUE TITLE
Overview connection not at all obvious

### ISSUE THREAD

**Issue by mcirsta** [F1ash/qt-virt-manager#17]
OK so you might attribute this to user error or me not knowing how to use the program but here's what I did:
1. Open qt-virt-manager without starting the libvirtd service ( now info about the libvirt service not started , would have been helpful )
2. Start libvirtd service and restart qt-virt-manager
3. Create a connection to qemu and open it
4. Try to "Create virtual domain manually" here the naming is a bit confusing, I wanted to create a VM instance in this case ( for qemu ). Note that at this step the button for this was active, the app started with this button active and never disabled it
5. Have a failure that was barely explained and only in the logs:  

✻ 23:50:25 Connection '':
EVENT: Read Data in _ failed.

✻ 23:50:25 Connection '':
EVENT: '' domain editor closed.

Yes, this is exactly what I thought  :)

Not satisfied with this I fired up QtCreator and began debugging. About 2 hours later I finally got it, there was this ptr_ConnPtr for the connection instance that was only set when "Overview Connection" was chosen. Again "Overview Connection" is not a name that suggested much to me, set connection to active or something would have been much more helpful.

Also if I just have one connection and I open that one I probably want that one to be the active one so "Overview Connection" could have been chosen automatically.

A message saying please choose an active connection would have also helped ... instead of some EVENT: Read Data in _ failed in the logs.

Please understand that this is from a first time user of the software who had no idea how it works and take this as constructive feedback.

Thanks for the software, it's really useful.

**Comment by F1ash** [comment]
Thank you for your fair comment. Will corrected with time.
