### ISSUE TITLE
is there qt-virt-manager for Ubuntu ?

### ISSUE THREAD

**Issue by ghost** [F1ash/qt-virt-manager#20]
thanks

**Comment by F1ash** [comment]
it can be build for Ubuntu, of course.

**Comment by ghost** [comment]
Can i connect it to docker engine/api?

**Comment by ghost** [comment]
Thanks

**Comment by morsik** [comment]
No. It's virt-manager for libvirt. Not for Docker.

**Comment by bentalexanderhaase** [comment]
Any instructions on how to build it?

**Comment by F1ash** [comment]
Something like:

1. unzip tarball with sources;
2. $ mkdir build-qt-virt-manager-Qt5-Debug
3. $ cd ./build-qt-virt-manager-Qt5-Debug
4. $ cmake -DBUILD_QT_VERSION=5 -DWITH_LIBCACARD=1 -DBUILD_TYPE=Debug -DUSE_SPICE_AUDIO=1 ../qt-virt-manager && make all

for required libraries and headers look README.md and [here](https://github.com/F1ash/qt-virt-manager/blob/master/qt-virt-manager.spec#L45-L59).
