### ISSUE TITLE
Wrong keyboard mapping 

### ISSUE THREAD

**Issue by TuxmAL** [F1ash/qt-virt-manager#21]
Opening a Windows XP VM, at logon keyboard mapping is wrong. My physical keyboard is IT_it but keys doesn't match. I cannot type at sign and hash sign ("@ #") and other char are in the wrong position.

**Comment by F1ash** [comment]
You use a spice or vnc viewer for it?

- VNC viewer has not keyboard scan codes interpretation. Maybe it implemented in his library.
- SPICE protocol use PC AT scan codes for keyboard
// See for: http://philipstorr.id.au/pcbook/book3/scancode.htm

**Comment by TuxmAL** [comment]
Hmmm.. it seems to me it's SPICE, I use the qt-virt-manager internal viewer, but also the external one, with the same results. Using virt-manager and his viewer I have no keyboard issue at all.

**Comment by F1ash** [comment]
Look: you must type on QWERTY layout on your physical comp\keyboard and national (or same) layout must be turn on in your remote system.

**Comment by TuxmAL** [comment]
My physical keyboard matches with the layout expected on the VM. I experimented the same behavoiur also wit a brand new VM with Debian 8. Can I do something to give more info?

**Comment by F1ash** [comment]
Sorry, physical keyboard layout must be turned on English and remote VM keyboard layout turned on national layout. Key sequence interpretator in Spice-Viewer "understand" only English layout (because uses QKeyEvent).

**Comment by TuxmAL** [comment]
Thank you, I verified that  and it worked, but since I have some issue with hash and at signs (mapped under AltGr on an italian keyboard) I will do some more testing.
