### ISSUE TITLE
Display VM. Worked only external connections

### ISSUE THREAD

**Issue by SergeyDjam** [F1ash/qt-virt-manager#25]
Don't worked display vm  if qemu+ssh connection. 
Worked only connected vnc://myserverIP:5901

**Comment by ghost** [comment]
I have the same issue, once I open a spice connection via SSH there is just a frame, but no content of the remove virtual machine will be displayed.

**Comment by F1ash** [comment]
I have not a time, but i know how improve the code for it. As workaround you can try build from this point <[e47d7cd583845e4998f78907bc887db139cd07d7](https://github.com/F1ash/qt-virt-manager/commit/e47d7cd583845e4998f78907bc887db139cd07d7)>
need a little wait...
