### ISSUE TITLE
Spice qemu connection with socket

### ISSUE THREAD

**Issue by g3ngr33n** [F1ash/qt-virt-manager#28]
Hello,

I would like to known if you can add the possibility to connect with qt5-remote-viewer trough socket ?

It work fine using spice://ip:port but doesn't work spice:///spice.sock (or spice+unix:///spice.sock), look like the port is mandatory

**Comment by F1ash** [comment]
In Viewer connection trough socket not implemented yet...

**Comment by F1ash** [comment]
if you can build application, then you can probe the last [changes](https://github.com/F1ash/qt-virt-manager/tree/51a939259933a7f140f66e445ccd6a008f723ddc) 51a939259933a7f140f66e445ccd6a008f723ddc
  (implemented for both internal\external Spice\VNC Viewers )

**Comment by g3ngr33n** [comment]
I most certainly can (emerge qt-virt-manager)

I will post a comment once the build will finish and tested

Thank you for your work

**Comment by g3ngr33n** [comment]
Using :
`spice:///?socket=/home/tux/spice.sock`

Return :
QNativeSocketEngine::bind() was not called in QAbstractSocket::UnconnectedState

Qemu is started as follow

> /usr/bin/qemu-system-x86_64 \
>    -monitor stdio \
>    -cpu Skylake-Client \
>    -vga qxl \
>   -spice unix,addr=/home/tux/spice.sock,disable-ticketing,gl=on \
>   -machine accel=kvm \
>    -m 1004 \
>    -hda /home/tux/.aqemu/Ubuntu_HDA.img \
>   -boot once=c,menu=off \
>   -net nic,vlan=0 \
>    -net user,vlan=0 \
>    -rtc base=localtime \
>   -name "Ubuntu"

**Comment by F1ash** [comment]
Need to check if libvirt create that socket for VM graphics (on runned VM)... When i checked it then i not set Socket (sill empty field) and libvirt created it automatically in /var/lib/libvirt/qemu/... This case must works.

**Comment by F1ash** [comment]
my probe to create graphic socket in $HOME is failed. Libvirt create socket in /var/lib/libvirt/qemu/ and when i call Viewer from app then Viewer display VM graphics.

**Comment by g3ngr33n** [comment]
You right, it is working very well using qt5-virt-manager, socket all good. I did not see how deep the options was very good job !

There is one thing doesn't work yet is :

libvirt: QEMU Driver error : unsupported configuration: qxl 3d acceleration is not supported

I cannot use 3D acceleration, do you have any idea about it ?

**Comment by F1ash** [comment]
if driver not support that then not use 3d acceleration (uncheck it in VM settings). Hmm.. 2d acceleration not supported in QXL too... Try another drivers. But i don't know about driver's acceleration. You can ask about in [IRC](https://libvirt.org/contact.html#irc)

**Comment by g3ngr33n** [comment]
It's ok I will find a way. Keep it up !

You should add cryptocurrency to your donation, yandex.ru does not accept credit card from my country :)

**Comment by F1ash** [comment]
maybe later ... :)  then i close issue.
