### ISSUE TITLE
Support for virt-viewer configuration files

### ISSUE THREAD

**Issue by rapgro** [F1ash/qt-virt-manager#29]
Can qt-virt-viewer work with .vv files? .vv files are (temporary) configuration files to start virt-viewer.

No idea where to find specification or documentation. Propably source available:
https://github.com/SPICE/virt-viewer/blob/master/src/virt-viewer-file.c

**Comment by F1ash** [comment]
[specification or documentation here](https://github.com/SPICE/virt-viewer/blob/master/man/remote-viewer.pod#connection-file)
Will implement when have a time... It is not difficult.

**Comment by rapgro** [comment]
see also https://github.com/UPC/ravada/issues/474

**Comment by rapgro** [comment]
Does not work in combination with ravada. I see a message "Getting the address data is failed".

Here is a sample generated with ravada:
```
[virt-viewer]
type=spice
host=192.168.0.143
port=5901
password=%s
fullscreen=1
title=Fedora26Xfce-ravada - Press SHIFT+F12 to exit
enable-smartcard=0
enable-usb-autoshare=1
delete-this-file=1
usb-filter=-1,-1,-1,-1,0
;tls-ciphers=DEFAULT
;host-subject=O=192.168.0.143,CN=?
;ca=CA
toggle-fullscreen=shift+f11
release-cursor=shift+f12
secure-attention=ctrl+alt+end
;secure-channels=main;inputs;cursor;playback;record;display;usbredir;smartcard
```

**Comment by rapgro** [comment]
Please use the key named host instead of address.
https://github.com/F1ash/qt-virt-manager/blob/abbcbb8957b6c68980e3d4556baa51b0f7395a1b/src/vm_viewer/vm_viewer_only.cpp#L125
https://github.com/SPICE/virt-viewer/blob/master/src/virt-viewer-file.c#L1150

Any key named address is not documented.
https://github.com/SPICE/virt-viewer/blob/master/man/remote-viewer.pod#connection-file

**Comment by F1ash** [comment]
i think that problem with encrypted graphics stream because qt-remote-viewer can use encrypted graphics stream only by ssh-tunnel on graphics socket in remote VM. Without encrypted graphics stream viewer can work with *.vv files.

**Comment by rapgro** [comment]
Password option is not supported. It works if no password used for libvirt settings.

**Comment by F1ash** [comment]
clear... will be implemented in new version. or if you wish i can push changes tomorrow for building and testing.
