### ISSUE TITLE
VM viewer toolbar changes window size when attached to window

### ISSUE THREAD

**Issue by bitlord** [F1ash/qt-virt-manager#33]
Steps to reproduce:
When you open a VM viewer, move the mouse to the top, toolbar shows up, you grab it by the left handle (click) and drag it to top, left or right of the window, it allows to be attached to the window. After you attach it, VM viewer window starts resizing/shrinking, and in the end toolbar detaches in most situations (all?).

I'm not sure if this also causes toolbar not to follow the window anymore. (related, or different bug)

Currently I'm running this on gentoo unstable (~amd64), qtcore-5.9.4 and plasma desktop.

Quick edit: I'm running git snapshot from today.

**Comment by rapgro** [comment]
Reproducible with version 0.53.83 in Fedora 27.

**Comment by F1ash** [comment]
I decide to drop attaching toolbar for avoid resizing loop...
try the 0.57.86 version (at evening).
