### ISSUE TITLE
[information] spice-gtk

### ISSUE THREAD

**Issue by g3ngr33n** [F1ash/qt-virt-manager#38]
Hello,

I would like to known if it possible to build qt-virt-manager without spice-gtk but with spice protocol support.

Is spice-gtk in anyway, required for qt-virt-manager ? It is possible to add it as soft dependencies ?

Thanks,

**Comment by F1ash** [comment]
`qt-virt-manager` don't contain `spice-gtk`. it use [`spice-client-glib`](https://www.spice-space.org/spice-gtk.html) API only for build (`spice-glib-devel` and `spice-protocol` packages in Fedora) and `spice-vdagent` in package requires.

**Comment by g3ngr33n** [comment]
Exactly the informations I needed, thanks !
