### ISSUE TITLE
Failed at building lxc viewer

### ISSUE THREAD

**Issue by XenGi** [F1ash/qt-virt-manager#7]
Failed at building some lxc stuff.

```
[ 63%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/vm_viewer.cpp.o
[ 63%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/viewer_toolbar.cpp.o
[ 63%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/lxc/lxc_viewer.cpp.o
[ 63%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/lxc/lxc_viewer_thread.cpp.o
[ 64%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/spice/spice_viewer.cpp.o
[ 64%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/qterminal/properties.cpp.o
[ 64%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/qterminal/bookmarkswidget.cpp.o
[ 64%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/qterminal/tabwidget.cpp.o
[ 64%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/qterminal/termwidgetholder.cpp.o
[ 64%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/qterminal/propertiesdialog.cpp.o
[ 64%] Building CXX object CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/qterminal/mainwindow.cpp.o
/tmp/yaourt-tmp-xengi/aur-virt-manager-qt5/src/qt-virt-manager/src/vm_viewer/lxc/lxc_viewer.cpp: In member function ‘void LXC_Viewer::setTerminalParameters()’:
/tmp/yaourt-tmp-xengi/aur-virt-manager-qt5/src/qt-virt-manager/src/vm_viewer/lxc/lxc_viewer.cpp:111:32: error: ‘class TermWidgetImpl’ has no member named ‘screenLinesCount’
             int l = t->impl()->screenLinesCount();
                                ^
/tmp/yaourt-tmp-xengi/aur-virt-manager-qt5/src/qt-virt-manager/src/vm_viewer/lxc/lxc_viewer.cpp:116:20: error: ‘class TermWidgetImpl’ has no member named ‘startTerminalTeletype’
         t->impl()->startTerminalTeletype();
                    ^
CMakeFiles/qt5-virt-manager.dir/build.make:6947: recipe for target 'CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/lxc/lxc_viewer.cpp.o' failed
make[2]: *** [CMakeFiles/qt5-virt-manager.dir/src/vm_viewer/lxc/lxc_viewer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/qt5-virt-manager.dir/all' failed
make[1]: *** [CMakeFiles/qt5-virt-manager.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by F1ash** [comment]
You must have qtermwidget source with the patch for qt-virt-manager
(https://github.com/qterminal/qtermwidget/commits/master : not older the da6838df1ab5a919c32cde68017518ac7b8ba0e5 commit).

**Comment by Dravigon** [comment]
dude for arch i used qtermwidget-git and it said to have he patch but still i get the same error

Building CXX object CMakeFiles/qt4-virt-manager.dir/src/vm_viewer/lxc/lxc_viewer.cpp.o
/home/dravigon/New Folder/qt-virt-manager/src/vm_viewer/lxc/lxc_viewer.cpp: In member function 'void LXC_Viewer::setTerminalParameters()':
/home/dravigon/New Folder/qt-virt-manager/src/vm_viewer/lxc/lxc_viewer.cpp:140:32: error: 'class TermWidgetImpl' has no member named 'screenLinesCount'
             int l = t->impl()->screenLinesCount();
                                ^
/home/dravigon/New Folder/qt-virt-manager/src/vm_viewer/lxc/lxc_viewer.cpp:145:20: error: 'class TermWidgetImpl' has no member named 'startTerminalTeletype'
         t->impl()->startTerminalTeletype();
                    ^
CMakeFiles/qt4-virt-manager.dir/build.make:8595: recipe for target 'CMakeFiles/qt4-virt-manager.dir/src/vm_viewer/lxc/lxc_viewer.cpp.o' failed
make[2]: **\* [CMakeFiles/qt4-virt-manager.dir/src/vm_viewer/lxc/lxc_viewer.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/qt4-virt-manager.dir/all' failed
Makefile:127: recipe for target 'all' failed
make[1]: **\* [CMakeFiles/qt4-virt-manager.dir/all] Error 2
make: **\* [all] Error 2
00:17:09: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project qt4-virt-manager (kit: Desktop)
When executing step "Make"
00:17:09: Elapsed time: 06:07.

**Comment by F1ash** [comment]
https://github.com/lxde/qtermwidget/commit/90008c9db9fecbe8bfc24f09b896ac8839663ed6
try for >qt5.4 or use early git-commit.

**Comment by Dravigon** [comment]
how to change version , help me here man im a newbi to project editing
and by the way i dont have any version less than qt 5.5 installed

**Comment by F1ash** [comment]
oh... then use -DBUILD_QT_VERSION=5 to build for Qt5 version in cmake args

**Comment by Dravigon** [comment]
thanks man that totally worked can i contact u via gitter if i need any help??

**Comment by F1ash** [comment]
issues with application write here

**Comment by Dravigon** [comment]
yeah sure
bu other than that gitter

**Comment by F1ash** [comment]
gitter is created. Answer -- when free time occures.
https://gitter.im/F1ash/qt-virt-manager
