### ISSUE TITLE
incorrect fsf address

### ISSUE THREAD

**Issue by rapgro** [F1ash/qt-virt-manager#8]
In those files:
qt-virt-manager-0.16.38/src/vm_viewer/qterminal/config.h
qt-virt-manager-0.16.38/src/vm_viewer/qterminal/main.cpp
qt-virt-manager-0.16.38/src/vm_viewer/qterminal/tabwidget.cpp
qt-virt-manager-0.16.38/src/vm_viewer/qterminal/tabwidget.h
qt-virt-manager-0.16.38/src/vm_viewer/qterminal/term_mainwindow.cpp
qt-virt-manager-0.16.38/src/vm_viewer/qterminal/term_mainwindow.h

Current license version:
https://www.gnu.org/licenses/gpl-2.0.txt

**Comment by F1ash** [comment]
in other Fedora projects it is permitted.
I think that it is not critical, because the full text of the license is given in a separate file and the versions of the licenses is same one

**Comment by rapgro** [comment]
True but I'm encouraged as the Fedora package maintainer to inform upstream about this discrepancy. It would be nice to see it fixed in a further release.

**Comment by F1ash** [comment]
ok, i will to erase this incorrect license texts at next release... This is a better and simple decision.
